In [14]:
import torch 
import torch.nn.functional as F

In [15]:
target = torch.FloatTensor([[.1, .2, .3],
                             [.4, .5, .6],
                             [.7, .8, .9]])

In [16]:
x = torch.rand_like(target) # 0 ~ 1 범위에서 랜덤값으로 target 과 같은 shape의 텐서를 생성
x.requires_grad = True      # x 를 미분 가능한 텐서로 설정하여. backward() 호출 시 x에 대한 기울기 자동 계산 

x

tensor([[0.3663, 0.5940, 0.6815],
        [0.6202, 0.7916, 0.8917],
        [0.2463, 0.7045, 0.9785]], requires_grad=True)

In [17]:
loss = F.mse_loss(x, target) # x와 target간의 평균 제곱오차(MSE) 계산 (x는 예측값, target은 정답값으로 가정)

loss

tensor(0.0902, grad_fn=<MseLossBackward0>)

In [18]:
threshold = 1e-5        # 손실함수 종료 기준값
learning_rate = 1.      # 가중치 업데이트에 사용할 학습률
iter_cnt = 0            # 반복 횟수 카운터 초기화

while loss > threshold:                     # 손실이 임계값보다 클 동안 반복
    iter_cnt += 1                           # 반복 횟수 증가

    loss.backward()                         # loss에 대한 역전파 수행 (∂loss / ∂x 계산)

    x = x - learning_rate * x.grad          # gradient descent 방식으로 x를 업데이트

    x.detach_()                             # 기존 계산 그래프에서 x 분리 
    x.requires_grad_(True)                  # 다음 반복을 위해 gradient 추적 다시 활성화

    loss = F.mse_loss(x, target)            # 업데이트된 x로 새로운 손실 계산

    print(f"{iter_cnt}번째 Loss: {loss}")    # 현재 반복의 손실 값 출력
    print(x)

1번째 Loss: 0.054543547332286835
tensor([[0.3072, 0.5064, 0.5967],
        [0.5713, 0.7268, 0.8269],
        [0.3471, 0.7257, 0.9610]], requires_grad=True)
2번째 Loss: 0.03299547731876373
tensor([[0.2611, 0.4383, 0.5308],
        [0.5332, 0.6764, 0.7765],
        [0.4255, 0.7422, 0.9475]], requires_grad=True)
3번째 Loss: 0.019960228353738785
tensor([[0.2253, 0.3854, 0.4795],
        [0.5036, 0.6372, 0.7373],
        [0.4865, 0.7551, 0.9369]], requires_grad=True)
4번째 Loss: 0.01207470428198576
tensor([[0.1975, 0.3442, 0.4396],
        [0.4806, 0.6067, 0.7068],
        [0.5340, 0.7651, 0.9287]], requires_grad=True)
5번째 Loss: 0.007304450497031212
tensor([[0.1758, 0.3121, 0.4086],
        [0.4627, 0.5830, 0.6830],
        [0.5709, 0.7728, 0.9223]], requires_grad=True)
6번째 Loss: 0.004418742377310991
tensor([[0.1590, 0.2872, 0.3844],
        [0.4488, 0.5646, 0.6646],
        [0.5996, 0.7789, 0.9174]], requires_grad=True)
7번째 Loss: 0.002673066221177578
tensor([[0.1459, 0.2678, 0.3657],
        [0.43