## 파이토치 시작


In [126]:
import torch

In [127]:
a = torch.FloatTensor([ [1, 2],
                        [3, 4] ])
b = torch.FloatTensor([ [1, 2],
                        [1, 2] ])
print(a.size()) # == shape 
print(b.size()) # == shape 

torch.Size([2, 2])
torch.Size([2, 2])


In [128]:
c = torch.matmul(a, b) # a 와 b 의 행렬곱 == a @ b
c

tensor([[ 3.,  6.],
        [ 7., 14.]])

- 1D * 1D => 내적 (dot product)
- 2D * 2D => 행렬 곱
- 3D * 3D => 배치 행렬 곱

## 파이토치 텐서값 할당


In [129]:
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])
ft

tensor([[1., 2.],
        [3., 4.]])

딥러닝에서는 가중치, 출력값, 손실, 기울기 등을 모두 실수연산 해야한다.

정수형은 미분  불가 및 기울기 계산 불가하여 사용하지 않는다.

그래서 신경망 연산의 기본타입은 FloatTenser 이다.

In [130]:
lt = torch.LongTensor([[1, 2],
                        [3, 4]])

In [131]:
bt = torch.ByteTensor([[1, 0],
                        [0 ,1]])

과거에 Mask 또는 조건 필터링 용도로 사용했었음 

In [132]:
mask = torch.BoolTensor([True, False, True]) 
mask

tensor([ True, False,  True])

최근에는 BoolTenser로 사용하는것이 표준 

In [133]:
x = torch.FloatTensor(3, 2) # shape 이 (3, 2 )인 텐서 생성 

In [134]:
torch.zeros(3, 2) # shape 이 (3, 2)인 0인 텐서 생성


tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [135]:
torch.ones(3, 2) # shape 이 (3, 2)인 1인 텐서 생성

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [136]:
torch.randn(3, 2 ) # shape 이 (3, 2 ) 인 정규분포 난수 값을 가지는 텐서

tensor([[-0.0828, -1.4629],
        [-0.3535,  0.0442],
        [-0.2971, -0.5644]])

# Numpy의 호환성

In [137]:
import numpy as np

x = np.array([[1, 2],
              [3, 4]])

print(x,type(x))


[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [138]:
x = torch.from_numpy(x) # Numpy ndarray 를 pytorch Tensor로 변환
print(x,type(x))


tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [139]:
x = x.numpy() # pytorch Tensor 를 numpy ndarray 로 변환 
print(x,type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [140]:
ft.long() # LongTenser 타입으로 변환, 소수점은 버림 

tensor([[1, 2],
        [3, 4]])

정수형으로 변환,주로 분류 문제에서 정답 라벨에 사용한다

In [141]:
lt.float() # FloatTenser 타입으로 변환

tensor([[1., 2.],
        [3., 4.]])

정수형 텐서를 연산,학습용 입력으로 사용할 때 & 가중치 계산, 신경망 입력시에는 Float 형태로 입력한다

In [142]:
torch.FloatTensor([1, 0]).byte() # byteTensor로 변환

tensor([1, 0], dtype=torch.uint8)

In [143]:
torch.FloatTensor([1, 0]).bool() # boolTenser로 변환

tensor([ True, False])

In [144]:
x = torch.FloatTensor([ [[1, 2],
                        [3, 4]],
                        [[5, 6],
                         [7, 8]],
                         [[9, 10],
                          [11, 12]]
                          ]
) # 3개의 배치, 2행 2열

print(x.size()) # pytorch 스타일


torch.Size([3, 2, 2])


## 텐서의 차원수

In [145]:
print(x.dim()) # 텐서의 차원 수
print(len(x.size())) # 길이 -> 차원 수 

3
3


## 특정 차원에 있는 요소의 개수

In [146]:
print(x.size(1)) # 1번축(axis = 1)의 크기를 가져옴
print(x.shape[1]) # 1번축(axis = 1)의 크기를 가져옴

2
2


## 마지막 차원의 요소 개수 

In [147]:
print(x.size(-1)) # 마지막 축의 크기를 가져옴 
print(x.shape[-1])  # 마지막 축의 크기를 가져옴

2
2


## 텐서 연산

In [148]:
a = torch.FloatTensor([[1, 2],
                        [3, 4]])
b = torch.FloatTensor([[2, 2],
                        [3, 3]])
a + b                                                

tensor([[3., 4.],
        [6., 7.]])

In [149]:
a - b

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [150]:
a * b

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [151]:
a / b

tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])

In [152]:
a == b # bool 형태로 반환

tensor([[False,  True],
        [ True, False]])

In [153]:
a != b

tensor([[ True, False],
        [False,  True]])

In [154]:
a ** b

tensor([[ 1.,  4.],
        [27., 64.]])

## 제자리 연산

In [155]:
print(a)
print(a.mul(b)) # a * b
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])


In [156]:
print(a.mul_(b)) # 제자리 수행. _(언더바)가 붙은 연산은 원본 tensor 를 직접 바꾼다 . in-place 연산
print(a)

tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


## Sum , Mean (차원 축소 작업)

In [157]:
x = torch.FloatTensor([[1, 2],
                        [3, 4]])
print(x.size())

y = x.sum()

print(y) 
print(y.size())

torch.Size([2, 2])
tensor(10.)
torch.Size([])


In [158]:
x = torch.FloatTensor([[1, 2],
                        [3, 4]])
print(x.size())

z = x.mean()

print(z) 
print(z.size())

torch.Size([2, 2])
tensor(2.5000)
torch.Size([])


In [159]:
print(x)
print(x.sum(dim = 0)) # 첫 번째 차원 (행) 방향으로 합산( 각 열의 합 )
print(x.sum(dim = -1)) # 마지막 차원 (열) 방향으로 합산( 각 행의 합 )

tensor([[1., 2.],
        [3., 4.]])
tensor([4., 6.])
tensor([3., 7.])


x.sum(dim = 0) : 행 축(dim = 0) 을 제거하면서 합산 
-> 행 축에 따라 값들을 더한다.
-> 해당 축은 사라진다.
-> 남은 것은 열 축

x.sum(dim = -1) : 마지막 차원인 열 축(dim = -1) 을 제거하면서 합산 
-> 열 축에 따라 값들을 더한다.
-> 해당 축은 사라진다.
-> 남은 것은 행 축

dim()은 기준 축 보다는 "재거할 축"
연산 결과는 제거되지 않는 축 기준으로 해석

Broadcast : 텐서의 차원(크기)가 다를때, 연산을 위해 자동으로 차원을 확장해서 차원을 맞춰주는 기능

In [160]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[4, 8]])


In [161]:
z = x + y
print(z.size())

torch.Size([1, 2])


In [162]:
x = torch.FloatTensor([[1, 2],
                       [3 ,4]])
y = 1 
print(x, x.size())

tensor([[1., 2.],
        [3., 4.]]) torch.Size([2, 2])


In [163]:
z = x + y
print(z, z.size())

tensor([[2., 3.],
        [4., 5.]]) torch.Size([2, 2])


y = 1 => 

[[1, 1],
[1, 1]]

=> x 와 동일한 shape 으로 브로드캐스팅

In [164]:
x = torch.FloatTensor([[1, 2],
                       [4 ,8]])
y = torch.FloatTensor([[3, 5]])

print(x.size())
print(y.size())

torch.Size([2, 2])
torch.Size([1, 2])


In [165]:
z = x + y

print(z, z.size())

tensor([[ 4.,  7.],
        [ 7., 13.]]) torch.Size([2, 2])


y = [[3, 5]] =>

[[3, 5],
[3, 5]]

 x의 행 수만큼 복제

In [166]:
x = torch.FloatTensor([[[1, 2]]])
y = torch.FloatTensor([3, 5])

print(x.size())
print(y.size())

torch.Size([1, 1, 2])
torch.Size([2])


In [167]:
z = x + y

print(z, z.size())

tensor([[[4., 7.]]]) torch.Size([1, 1, 2])


x = (1 1 2)

y =     (2)

=> y = x와 같은 shape인(1 1 2)로 자동 확장

y =  [3, 5] => [[[3, 5]]]

In [168]:
# Tensor + Tensor
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3],
                       [5]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([2, 1])


In [169]:
z = x + y

print(z, z.size())

tensor([[4., 5.],
        [6., 7.]]) torch.Size([2, 2])


x : (1, 2)
y : (2, 1)

마지막 차원 2 vs 1 (2차원으로 확장)
앞차원 1 vs 2 (2차원으로 확장)
=> 둘다 브로징캐스팅이 일어났다


x = [[1, 2]]
==> 

[[1, 2],
     [1, 2]]

y = [[3],[5]]
=> 

[[3, 3],
     [5, 5]]

In [170]:
x = torch.FloatTensor([[[1, 2],
                       [4 ,8]]])    # 1 2 2 
y = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]]) # 3 3

print(x.size())
print(y.size())

torch.Size([1, 2, 2])
torch.Size([3, 3])


|차원 |X|y|호환여부|
|---|---|--|----|
|-1차원| 2| 3| 다르고,둘다 1아님| 
|-2차원| 2| 3| 다르고,둘다 1아님| 
|-3차원| 1| -|자동확장가능| 

브로드캐스팅 조건: 각 차원의 값이 같거나, 하나가 1일 경우에 자동 확장 가능
=> -1, -2 차원의 shape이 맞지 않아 브로드 캐스팅 실패
가능하게 만들어주려면 차원이 맞거나, 어느 한쪽이 1이면 가능하다.

In [171]:
# reshape : 텐서 모양을 변경해준다.

x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                        [[5, 6],
                         [7, 8]],
                        [[9, 10],
                         [11,12] ]]
                         )# 3 2 2
print(x.size())

torch.Size([3, 2, 2])


In [172]:
print(x.reshape(12)) # shape을 명시적으로 지정(원소12개 짜리 1차원 텐서로 바꾼다.
print(x.reshape(-1)) # -1 : 자동계산 ( 전체 원소수 12를 기준으로 자동변경)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


reshpae(-1)은 텐서를 1차원으로 펼칠때 가장 자주 쓰는 방식이다

In [173]:
    print(x.reshape(3, 4)) # 명시적으로 (3, 4)형태로 만든다
    print(x.reshape(3, -1)) # 3행은 고정, (-1 자동계산)하여 => 3 x ? = 12 -> ? = 4 => (3, 4)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


reshape 은 원소 갯수는 유지 

-1 은 자동으로 계산해주는 자리표시자

-1 은 한 번만 사용 가능

In [174]:
print(x.reshape(3, 1, 4)) # 1행 4열짜리 행렬 3개
print(x.reshape(-1, 1, 4)) # 1행 4열 짜리 행렬 3개

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [175]:
print(x.reshape(3, 2, 2, 1)) # 2 * 2 행렬에 채널 1를 붙인 데이터 3개

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


reshape() 대신 view()를 사용할 수도 있다.

view는 연속된 메모리 구조일때만 사용한다.

reshape()는 내부적으로 필요하면 데이터 복사도 수행하며 유연하게 작동하기 때문에 주로 사용한다

squeeze() : 텐서에서 크기가 1인 차원만 제거한다

In [176]:
x = torch.FloatTensor([[[1, 2],
                       [4 ,8]]])  # size = 1 2 2

print(x.size())

torch.Size([1, 2, 2])


In [177]:
print(x.squeeze())

tensor([[1., 2.],
        [4., 8.]])


squeeze()함수는 크기가 1인 차원을 자동으로 제거해준다. 그래서 텐서 의 차원을 줄여준다.


squeeze(dim): dim에 설정한 특정 차원만 제거한다. 지정한 차원의 크기가 1일경우에만 제거한다

In [178]:
print(x.squeeze(0).size()) # dim=0 의 크기를확인해서 1이면 제거
print(x.squeeze(1).size()) # dim=1 의 크기를확인해서 1이면 제거
print(x.squeeze(2).size()) # dim=2 의 크기를확인해서 1이면 제거

torch.Size([2, 2])
torch.Size([1, 2, 2])
torch.Size([1, 2, 2])


unsqueeze():특정위치에 새차원을 추가한다


In [179]:
x = torch.FloatTensor([[1, 2],
                       [4 ,8]])
print(x.size())

torch.Size([2, 2])


In [180]:
print(x.unsqueeze(2))     # 2번 차원에 크기 1인 축 추가 (2, 2) -> (2, 2, 1)
print(x.unsqueeze(-1))     #마지막 차원에 크기 1인 축 추가 (2, 2) -> (2, 2, 1)
print(x.reshape(2,2,-1))    # 전체 원소수 유지(2*2 = 4), -1 : 자동계산 => 1-> (2, 2, 1)

tensor([[[1.],
         [2.]],

        [[4.],
         [8.]]])
tensor([[[1.],
         [2.]],

        [[4.],
         [8.]]])
tensor([[[1.],
         [2.]],

        [[4.],
         [8.]]])


### 텐서 자르기 & 붙이기 

In [181]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                        [[5, 6],
                         [7, 8]],
                         [[9,10],
                          [11,12]]]
                          )

### 특정 차원에 접근

In [182]:
print(x[0])         # 첫 번째 차원(dim = 0 ) 접근
print(x[0,:])       # 첫 번째 차원의 그 다음 차원은 : 로 전체 선택, 세번쨰 차원은 생략()
print(x[0, :, :])   # 첫 번째 차원의 그 다음 차원은 : 로 전체 선택, 세번쨰 차원도 동일하게 선택

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])


뒷 차원의 : 은 생략 가능하다. 생략하면 자동으로 전체(:)로 처리된다


In [183]:
print(x[-1])         # 첫 번째 차원에서 마지막 요소 선택, 나머지 차원은 자동선택
print(x[-1,:])       # 첫 번쨰 차원에서 마지막 요소 선택, 두번쨰 차원 전체 선택, 세번째 차원은 생략(
print(x[-1, :, :])   # 첫 번째 차원에서 마지막 요소 선택, 두번쨰, 세번째 차원은 전체 선택

tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])


음수 인뎅싱 -1 은 마지막 요소를 의미한다.
뒤 차원의 : 는 생략해도 동일한 효과 이다 

In [184]:
# 각 배치에서 첫번째 행만 가져온다
print(x[:,0])
# 각 배치에서 첫번째 열만 가져온다
print(x[:,:,0])

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])
tensor([[ 1.,  3.],
        [ 5.,  7.],
        [ 9., 11.]])


print(x[:,0]) : [3, 2] 
배치 수는 그대로 3유지 
행 차원이 선택되어 제거 
열 차원 2 유지

print(x[:,:,0]) : [3, 2] 
배치 수는 그대로 3유지 
행 차원 2 유지
열 차원이 선택되어 제거 

범위로 접근하면 텐서의 차원수가 유지된다아아아아아아

In [185]:
print(x[1:3, : , :].size()) # 배치 인덱스 1, 2 선택, 나머지 차원은 전체 유지
print(x[:, :1, :].size())   # 모든 배치.행에서 앞의1개만 선택 열은 전체 유지 
print(x[:, :-1 , :].size())  # 모든 배치.마지막 행을 제외한 전체 행 열은 전체 유지 


torch.Size([2, 2, 2])
torch.Size([3, 1, 2])
torch.Size([3, 1, 2])


| 구분 | 기능 | 사용 코드 | 들어가는 값 | 설명 |
|------|------|-----------|-------------|------|
| Tensor 생성 | 텐서 만들기 | `torch.tensor(data)` | data → 리스트 / 중첩 리스트 | 기본 Tensor 생성 |
| 연속값 생성 | 숫자 생성 | `torch.arange(start, end)` | start, end → 정수 | 연속 값 생성 |
| Shape 확인 | 차원 구조 확인 | `x.shape`, `x.size()` | x → Tensor | 데이터 구조 파악 |
| Reshape | 형태 변경 | `x.reshape(a, b)` | a, b → 새 차원 | 값 유지, 모양만 변경 |
| 자동 차원 | 차원 자동 완성 | `x.reshape(3, -1)` | 3 고정, -1 자동 | 나머지 차원 계산 |
| Indexing | 행 선택 | `x[i]` | i → 행 인덱스 | 특정 행 선택 |
| Indexing | 열 선택 | `x[:, j]` | : 전체, j → 열 인덱스 | 특정 열 선택 |
| Indexing | 다차원 접근 | `x[i, :, :]` | 각 차원 인덱스 | 다차원 접근 |
| Broadcasting | 자동 확장 | `x + y` | x, y → Tensor | 차원 같거나 한쪽이 1 |
| 행렬 연산 | 행렬 곱 | `torch.matmul(a, b)` | a, b → Tensor | 행렬 계산 |
| 합계 | 합 계산 | `x.sum(dim)` | dim → 기준 축 | 축 기준 합 |
| 평균 | 평균 계산 | `x.mean(dim)` | dim → 기준 축 | 축 기준 평균 |
| 최대값 | 최대 | `x.max(dim)` | dim → 기준 축 | (값, 위치) 반환 |
| 위치 | 최대 위치 | `x.argmax(dim)` | dim → 기준 축 | 최대값 위치 |
| Top-k | 상위 k개 | `torch.topk(x, k, dim)` | k → 개수, dim → 기준 축 | 후보 추출 |

split():텐서를 원하는 모양으로 나눕니다


In [186]:
x = torch.FloatTensor(10, 4)

x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [187]:
splits = x.split(4, dim=0) #0 번 차원(dim=0) 을 따라 4개씩 잘라라 (반환값:튜플)


for s in splits:
    print(s.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


split(4, dim=0) # 0번 축에 따라 4개씩 나누며, 남은 데이터는 마지막 조각으로 반환한다

chunk() : 텐서를 청크 수로 나눕니다

In [188]:
x = torch.FloatTensor(8, 4) 

chunks = x.chunk(3, dim = 0 ) # 0번 차원(dim = 0 )을 기준으로 3조각으로 나눈다

for c in chunks:
    print(c.size())

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([2, 4])


split(size,din) : 기준은 크기. 마지막에 나머지 조각을 만든다.

chunk(n, dim) : 기준은 갯수. 최대한 군등하게 분할한다 (나머지 최소화)

index_select(): 차원 인덱스를 사용하여 요소를 선택한다.

In [189]:
x = torch.FloatTensor([[[1, 1],
                       [2, 2]],
                       [[3, 3],
                        [4, 4]],
                        [[5, 5],
                         [6, 6]]]) # size = 3 2 2

indice = torch.LongTensor([2,1])
print(x.size()) 
print(indice.size())

torch.Size([3, 2, 2])
torch.Size([2])


In [190]:
y = x.index_select(dim=0, index= indice) #0 번 차원 (dim=0)에서 indice에서 지정한 순서대로 선택
                                         # 먼저 x[2], 그다음 x[1]
print(y)
print(y.size())                                         

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])
torch.Size([2, 2, 2])


index_select() 함수

순서가 유지됨 indice 에서 설정한 [2, 1] 순서 그대로 사용한다.

중복 인덱스도 가능하다.

결과 - 인덱스는 새로 생성된다 (원본x가 변할일은 없다)

index 는 반드시 LongTensor로 설정해야한다

In [191]:
# 중복선택
x.index_select(0, torch.LongTensor([0,0,2]))

tensor([[[1., 1.],
         [2., 2.]],

        [[1., 1.],
         [2., 2.]],

        [[5., 5.],
         [6., 6.]]])

index_select(dim, index) : 지정한 축에서 원하는 인덱스만 순서대로 선택하는 함수

cat(): 여러 텐서르 연결한다.

In [192]:
x = torch.FloatTensor(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)
y = torch.FloatTensor(
    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]]
)

print(x.size(), y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [193]:
z = torch.cat([x,y], dim= 0)
print(z)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])


cat()의 규칙

븥이는 축을 제외한 나머지 차원은 반드시 동일

(행,열) 기준일때

dim=0 -> 행 증가

dim=1 -> 열 증가

In [194]:
z = torch.cat([x,y], dim= 1)

print(z)
print(z.size())

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


torch.cat 함수는 지정한 축을 기준으로 텐서를 이어 붙인다.
그 외 차원은 모두 같아야 한다.

stack() : 여러 텐서를 쌓아 새로운 차원을 만든다.

In [195]:
z = torch.stack([x,y])

print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


torch.stack()함수는 기존 텐서들을 이용해 새로운 차원으로 쌓는다.
x, y 각각의 shape(3,3)은 그대로 유지하면서 맨 앞에 새로운 차원  (dim=0) 이 하나 생기게 된다

| 함수 | 차원 변화 | 의미 |
|------|----------|------|
| cat  |차원 수 동일|-----|
|stack|차원 +1 |새로운 축을 만들어 쌓음|

In [196]:
print(torch.cat([x,y], dim = 0).size())
print(torch.stack([x,y], dim = 0).size())

torch.Size([6, 3])
torch.Size([2, 3, 3])


쌓을 차원을 지정할 수 있다. 기본값은 0이다

In [197]:
z =torch.stack([x,y], dim =-1)
print(z)

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])


torch.stack(dim= -1 ) : 같은 위치의 값 들을 마지막 차원(feature 축 )으로 묶는다.

In [198]:
print(torch.stack([x,y], dim = 0).size()) # 맨 앞 차원 추가 ( 의미 : 텐서 묶음)
print(torch.stack([x,y], dim =-1).size()) # 멘 뒷 차원 추가  ( 의미 : feature / channel)

torch.Size([2, 3, 3])
torch.Size([3, 3, 2])


In [199]:
print(x)
print(y)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])


In [200]:
z = torch.stack([x,y])

print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


In [ ]:
# cat 함수와 unsqueeze 함수를 통해 같은 결과를 구현해 보세요
z = torch.cat([x.unsqueeze(0),y.unsqueeze(0)])
print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


torch.cat([], dim=0) : dim=0 방향으로 이어붙임

변수.unsqueeze(dim): 해당하는 dim위치에 크기 1인 새차원 추가

torch.cat([(1, 3, 3,), (1, 3, 3)], dim=0) => (2, 3, 3)


## 반복문 결과를 하나로 병합하기

In [208]:
result = []
for i in range(5):
    x = torch.FloatTensor(2,2) # shape 이 (2, 2). 값이 초기화되지 않은 랜덤 메모리값
    result += [x]               # (2,2) 텐서를 리스트에 하나씩 추가

result = torch.stack(result)    # 리스트에 들어있는 텐서들을 새로운 차원으로 쌓는다.
result.size()

torch.Size([5, 2, 2])

stack을 사용하려면 모든 텐서의 shape이 동일해야한다.

for문을 통해 리스트 -> 텐서로 묶으면 깔끔하게 병합 할 수 있다.

배치 데이터 생성할때 이러한 방식으로 많이 사용한다.

## 유용한 메서드


expend(): 크기가 1인 차원을 지정한 크기만큼 확장해서, 같은 값이 반복된 것처럼 보이게한다(메모리를 복사하지 않는다)

In [209]:
x = torch.FloatTensor([[[1, 2]],
                        [[3, 4]]]) # size() : 2 1 2

print(x.size())

torch.Size([2, 1, 2])


In [213]:
y = x.expand(2, 3, 2) #기존 shape : (2, 1, 2) -> 목표 shape : (2, 3, 2)
                            #dim = 1 의 크기를 1 => 3 으로 확장하고, 나머지 차원은 그대로 유지한다.
 #y = x.expand(*[2, 3, 2]) #같은 의미이다 (unpacking 해서 list 나 tuple 전달시에 이렇게 사용

print(y)
print(y.size())


tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


expand는 값을 복사하지 않는다.
내부적으로 같은 메모리를 여러번 참조 (메모리 효율이 좋다)

expand() 함수는 크기 1인 차원을 복사없이 늘려서 확장시키는 연산이다 

In [221]:
# expand의 기능을 cat 함수를 이용해서 똑같이 구현해 보세요 
y = torch.cat([x,x,x], dim = 1)

print(y)

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])


cat 함수는 실제 데이터를 복사.inplace 수정해도 안전

expand 함수는 메모리를 공유 inplace 수정을 하면 공유된 메모리값이 바뀔 위험성이있다

In [222]:
print(x.expand(2, 3, 2).size())
print(torch.cat([x,x,x],dim=1).size())

torch.Size([2, 3, 2])
torch.Size([2, 3, 2])


shape은 같지만 메모리복사 일어남/ 일어나지않음 차이가 있다

### randperm(n): 랜덤 순열 (0부터 n-1까지의 정수를 무작위로 섞은 순열 텐서를 반환. 중복은 없다) 

In [223]:
x = torch.randperm(10) #    0부터 9까지 정수를 무작위로 섞은 1차원Tenser생성

print(x)


tensor([6, 3, 5, 0, 8, 1, 2, 7, 9, 4])


argmax(): 최대값의 인덱스를 반환한다

In [225]:
x = torch.randperm(3**3).reshape(3, 3, -1) # 27개의 요소 => reshape (3, 3, 3) 3*3*3
print(x)

tensor([[[18, 21, 16],
         [ 9,  4, 26],
         [10, 20, 13]],

        [[19,  6, 11],
         [14,  1,  3],
         [ 2,  0, 22]],

        [[12, 17,  5],
         [23, 24,  7],
         [25, 15,  8]]])


In [ ]:
y = x.argmax(dim= -1 ) # 마지막 차원(열)에서 가장 큰 값의 인덱스를 반환하고, 설정한 차원은 삭제한다.

print(y)
print(y.size())

tensor([[1, 2, 1],
        [0, 0, 2],
        [1, 1, 0]])
torch.Size([3, 3])


argmax(dim=k)는 k번 차원에서 하나를 선택하고,그 해당 차원은 삭제한다

만약에 차원을 유지하고 싶다면 keepdim=True옵션을 설정

In [228]:
y =x.argmax(dim=-1,keepdim=True)
print(y)

tensor([[[1],
         [2],
         [1]],

        [[0],
         [0],
         [2]],

        [[1],
         [1],
         [0]]])


 topk():상위k 개의 값과 해당 인덱스를 튜플형태로 반환한다.
 

In [229]:
values,indices = torch.topk(x, k=1, dim = -1) # 마지막 차원에서 상위 1개의 (k=1)를 선택하여 값과 인덱스 반환

print(values)
print(values.size())

print(indices)
print(indices.size())

tensor([[[21],
         [26],
         [20]],

        [[19],
         [14],
         [22]],

        [[17],
         [24],
         [25]]])
torch.Size([3, 3, 1])
tensor([[[1],
         [2],
         [1]],

        [[0],
         [0],
         [2]],

        [[1],
         [1],
         [0]]])
torch.Size([3, 3, 1])


topk 옵션에 k=1로 하면 argmax+keepdim 옵션사용과 결과가 같다 

k=1 인 경우에도 topk는 차원을 줄이지 않는다

In [230]:
 #squeeze() 차원 크기가 1인 차원을 제거한다
print(values.squeeze(-1))
print(indices.squeeze(-1))

tensor([[21, 26, 20],
        [19, 14, 22],
        [17, 24, 25]])
tensor([[1, 2, 1],
        [0, 0, 2],
        [1, 1, 0]])


In [ ]:
print(x.argmax(dim= -1) == indices.squeeze(-1)) # 마지막 차원에서 최대값의 인덱스, indices와 같은지 확인
                                                # topk(k=1) 에서 나온 인덱스

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [236]:
_,indices = torch.topk(x, k=2, dim = -1) 
print(indices)
print(indices.size())
print(x.argmax(dim=-1)== indices[:,:,0])

tensor([[[1, 0],
         [2, 0],
         [1, 2]],

        [[0, 2],
         [0, 2],
         [2, 0]],

        [[1, 0],
         [1, 0],
         [0, 1]]])
torch.Size([3, 3, 2])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


indices.size() = (3, 3, 2)   
x.argmax(dim=-1) : 마지막 차원(열)의 각 위치의 최대값의 인덱스 -> shape : (3, 3)
indices[:, :, 0] : 가 2 인덱스 중에서 가장 큰 값의 인덱스만 선택 -> shape : (3, 3)

topk(k, dim)는 기본적으로 내림차순 정렬   
indicies[..., 0] : 최대값의 위치
indicies[..., 1] : 두번째로 큰 값의 위치

sort() 를 사용해서 topk () 구현하기


In [1]:
import torch
x = torch.randperm(3**3).reshape(3, 3, -1) # 27개의 요소 => reshape (3, 3, 3) 3*3*3
print(x)

tensor([[[11, 12, 20],
         [17, 16,  6],
         [ 0,  2, 25]],

        [[15, 18, 10],
         [19,  4, 22],
         [ 7,  5, 26]],

        [[ 8,  1, 13],
         [24, 14,  3],
         [23,  9, 21]]])


sort () : dim을 기준으로 정렬한다. 반환값은 (정렬된 값, 정렬 전 원래 index) 튜플

In [24]:
values , indices = torch.sort(x,dim= -1, descending= True) # 마지막 차원 (열) 을 기준으로 내림차순 정렬
print(values)           # 정렬 된 값
print(values.size())

print(indices)          # 정렬 전 인덱스 값
print(indices.size())

tensor([[[20, 12, 11],
         [17, 16,  6],
         [25,  2,  0]],

        [[18, 15, 10],
         [22, 19,  4],
         [26,  7,  5]],

        [[13,  8,  1],
         [24, 14,  3],
         [23, 21,  9]]])
torch.Size([3, 3, 3])
tensor([[[2, 1, 0],
         [0, 1, 2],
         [2, 1, 0]],

        [[1, 0, 2],
         [2, 0, 1],
         [2, 0, 1]],

        [[2, 0, 1],
         [0, 1, 2],
         [0, 2, 1]]])
torch.Size([3, 3, 3])


In [27]:
values , indices = torch.sort(x,dim= -1, descending= True) # 마지막 차원 (열) 을 기준으로 내림차순 정렬
values , indices = values[:,:,0] , indices[:,:,0]
values.size()
indices.size()

torch.Size([3, 3])

In [30]:
values , indices = torch.sort(x,dim= -1, descending= True) # 마지막 차원 (열) 을 기준으로 내림차순 정렬
values , indices = values[:,:,1] , indices[:,:,1]
print(values.size())
print(indices.size())

print(values.squeeze(-1).size())
print(indices.squeeze(-1).size())

torch.Size([3, 3])
torch.Size([3, 3])
torch.Size([3, 3])
torch.Size([3, 3])


sort() + 슬라이싱 방식은 topk와 동일한 결과를 만들어 낼 수 있다.

그러나 상위K 개만 필여할때는 topk를 쓰는것이 더 유용하다

masked_fill(): 마스크가 True 인 위치에 지정한 값을 채운다

In [32]:
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3, -1) # 0~8 요소를 가진  * 3 (-1이 자동계산)의 2차원 텐서

print(x)
print(x.size())

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([3, 3])


In [ ]:
mask = x > 4

mask # boolTensor

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])

In [ ]:
y = x.masked_fill(mask, value = -1) # mask가 True 인 위치만 -1로 채운다
print(y)        

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])


- 이런 패턴을 사용하는 경우
    - 이미지 padding 처리
    - loss 계산시에 무시할 값 처리
    - attention mask (집중할 단어)
    
    
이런 패턴에서 주로 사용한다

ones(), zeros(): 모든 요소가 1 또는 0 로 채워진 텐서를 생성한다

In [36]:
print(torch.ones(2, 3))
print(torch.ones(2, 3).size())

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])


In [38]:
print(torch.zeros(2, 3))
print(torch.zeros(2, 3).size())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])


In [39]:
x = torch.FloatTensor([[1, 2, 3],
                        [4, 5, 6]])


print(x)
print(x.size())

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [40]:
print(torch.ones_like(x))       # x 와 동일한 shape, 동일한 dtype으로 모든값을 1로 채운 텐서
print(torch.zeros_like(x))      # x 와 동일한 shape, 동일한 dtype으로 모든값을 0로 채운 텐서

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


ones_like(), zeros_like()는 기준 텐서와 동일한 형태의 초기화 텐서를 만들 때 사용한다